// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbesbwjsflwjtmjdcobo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRiZXNid2pzZmx3anRtamRjb2JvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwODkzMzAsImV4cCI6MjA2OTY2NTMzMH0.MUKbQeCrA7BQAR5F-4dVT3Nb-lNDGgaLZlqTaebgsY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});